version: 0.0
os: linux	
files:	
  - source: /index.html	  
    destination: /var/www/html/	    
  - source: /fold    
    destination: /home/ubuntu/fold
hooks:	
  BeforeInstall:	 
    - location: scripts/install_dependencies	   
      timeout: 300	     
      runas: root	     
    - location: scripts/start_server	    
      timeout: 300	     
      runas: root	      
  AfterInstall:
    - location: scripts/after_install
      timeout: 300
      runas: root